# safelist
branches:
  only:
  - master
  - Csi.AuthenticationGateway


language: csharp
dist: xenial
os: linux

mono: none
dotnet: 2.1.512

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

before_install:
  - sudo apt update
  - sudo apt install -y openssh-client sshpass lftp

script:
  - dotnet restore
  - dotnet build
  - pwd
  - dotnet publish Csi.AuthenticationGateway
  - ls -al
  - ls -al ./Csi.AuthenticationGateway/bin/Debug/netcoreapp2.1/publish/

after_success:
  - echo "pwd" | sshpass -p $SFTP_PASSWORD sftp -o StrictHostKeyChecking=no zhixian@plato.emptool.com
  - lftp -e "mirror -R ./Csi.AuthenticationGateway/bin/Debug/netcoreapp2.1/publish/ /var/www/csi-auth ;quit" -u zhixian,$SFTP_PASSWORD sftp://plato.emptool.com