# safelist
branches:
  only:
  - master
  - Csi.AuthenticationGateway


language: csharp
dist: xenial
os: linux

mono: none
dotnet: 2.1.512

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

before_install:
  - sudo apt update
  - sudo apt install -y openssh-client sshpass lftp

script:
  - dotnet restore
  - dotnet build
  - dotnet publish Csi.AuthenticationGateway --output ./public
  - ls -al

after_success:
  - echo "pwd" | sshpass -p $SFTP_PASSWORD sftp -o StrictHostKeyChecking=no zhixian@plato.emptool.com
  - lftp -e "mirror -R ./public /var/www/csi-auth ;quit" -u zhixian,$SFTP_PASSWORD sftp://plato.emptool.com